-- Doesn't work, you have to have your database mounted exclusively.
-- DROP DATABASE;

-- Displays code to drop all tables, in the database, in the output.
-- SELECT 'DROP TABLE ' ||table_name || ';' from user_tables;

DROP TABLE BIURA;
DROP TABLE PORTY;
DROP TABLE LODZIE;
DROP TABLE MODELE_LODZI;
DROP TABLE REJSY;
DROP TABLE KLIENCI;
DROP TABLE CZARTERY;
DROP TABLE KURSY;
DROP TABLE ATRAKCJE;
DROP TABLE PRACOWNICY;
DROP TABLE PORT_PRACOWNIK;
DROP TABLE LODZ_CZARTER;
DROP TABLE REJS_ATRAKCJA;
DROP TABLE REJS_KURS;
DROP TABLE REJS_PORT;
DROP TABLE KLIENT_REJS;
DROP TABLE REJS_LODZ;
DROP TABLE WLASCICIELE;
DROP TABLE POCZTY;
DROP TABLE ADRESY;